### ISSUE TITLE
Moore's Voting Algorithm & Trapping Rainwater Problem in C++

### ISSUE THREAD

**Issue by HellspawnXerxes** [abhaygupta08/Hacktober-2022#211]
I would like to contribute these two problems in the C++ folder of your repository. Also I will be really grateful to you if you tag this as mu Hacktoberfest 2022 contribution.

**Comment by aadii0408** [comment]
Hello sir, can you please assign this to me?  Also, I will be happy if you tag this as my Hacktoberfest 2022 contribution.
