### ISSUE TITLE
Spiral Matrix in C++.

### ISSUE THREAD

**Issue by akhilesh5056** [abhaygupta08/Hacktober-2022#324]
@abhaygupta08 Kindly assign me this issue under Hacktoberfest 2022.

**Comment by iamAditya01** [comment]
kindly assign me this one dear

**Comment by ajay-0707** [comment]
Could you please assign me this problem?

**Comment by iamAditya01** [comment]
Completed, merge it

**Comment by abhaygupta08** [comment]
@ajay-0707 Create a separate issue for you, then raise a PR.

**Comment by iamAditya01** [comment]
@abhaygupta08  bro accept the PR , its not getting reflected on my hacktober profile
